language: node_js
node_js:
  - "lts/carbon"
cache: npm

stages:
  - compile
  - test

env:
  - OPENCV4NODEJS_DISABLE_AUTOBUILD=1

jobs:
  include:
  - stage: compile
    script: npm run compile
  - stage: test
    script: npm test
